
image: ruby:2.4

cache:
  paths:
    - vendor/

before_script:
  - bundle install --path vendor

pages:
  script:
    - cd __source/jekyll
    - bundle exec jekyll build
  artifacts:
    paths:
      - public
  only:
    - master
