
before_script:
  - apt-get update -y
  - apt-get install -y locales
  - echo "en_US UTF-8" > /etc/locale.gen
  - locale-gen en_US.UTF-8
  - export LANG=en_US.UTF-8
  - export LANGUAGE=en_US:en
  - export LC_ALL=en_US.UTF-8

pugPrep:
  image: node:8.9.1
  script:
    - npm i -g npm@latest
    - npm i -g pug

pages:
  image: ruby:2.4
  script:
    - bundle install --deployment
    - cd __source/jekyll
    - bundle exec jekyll build
  artifacts:
    paths:
      - public
  only:
    - master
