
image: ruby:2.4

before_script:
  - export LC_ALL=en_US.UTF-8
  - bundle install --deployment

pages:
  script:
    - cd __source/jekyll
    - bundle exec jekyll build
  artifacts:
    paths:
      - public
  only:
    - master
