
image: ruby:2.4

before_script:
  - apt-get update -y
  - echo "=> Setting en_US UTF-8 locale..."
  - apt-get install -y locales
  - echo "en_US UTF-8" > /etc/locale.gen
  - locale-gen en_US.UTF-8
  - export LANG=en_US.UTF-8
  - export LANGUAGE=en_US:en
  - export LC_ALL=en_US.UTF-8
  - echo "=> Installing node..."
  - curl -SLO "https://nodejs.org/dist/v9.2.0/node-v9.2.0-linux-x64.tar.xz"
  - tar -xJf "node-v9.2.0-linux-x64.tar.xz" -C /usr/local --strip-components=1 --no-same-owner
  - ln -s /usr/local/bin/node /usr/local/bin/nodejs
  - echo "=> Installing node packages..."
  - npm i -g pug-cli
  - pug --version

pages:
  script:
    - bundle install --deployment
    - cd __source/jekyll
    - bundle exec jekyll build
  artifacts:
    paths:
      - public
  only:
    - master
