export default {
  "itp-ph-02-wd.jpg": { caption: "grass", order: 1 },
  "itp-ph-08-sq.jpg": { caption: "astratto", order: 2 },
  "itp-ph-02-sq.jpg": { caption: "astratto", order: 3 },
  "itp-ph-03-wd.jpg": { caption: "stripes", order: 4 },
  "itp-ph-18-wd.jpg": { caption: "19:49", order: 5 },
  "itp-ph-03-sq.jpg": { caption: "astratto", order: 6 },
  "itp-ph-04-sq.jpg": { caption: "astratto", order: 7 },
  "itp-ph-19-wd.jpg": { caption: "astratto", order: 8 },
  "itp-ph-14-wd.jpg": { caption: "rain", order: 9 },
  "itp-ph-10-sq.jpg": { caption: "Untitled", order: 10 },
  "itp-ph-01-sq.jpg": { caption: "astratto", order: 11 },
  "itp-ph-17-wd.jpg": { caption: "astratto", order: 12 },
  "itp-ph-05-wd.jpg": { caption: "ripped", order: 13 },
  "itp-ph-05-sq.jpg": { caption: "red", order: 14 },
  "itp-ph-06-sq.jpg": { caption: "astratto", order: 15 },
  "itp-ph-12-wd.jpg": { caption: "astratto", order: 16 },
  "itp-ph-13-wd.jpg": { caption: "untitled", order: 17 },
  "itp-ph-07-sq.jpg": { caption: "untitled", order: 18 },
  "itp-ph-09-sq.jpg": { caption: "astratto", order: 19 },
  "itp-ph-10-wd.jpg": { caption: "astratto", order: 20 },
  "itp-ph-16-wd.jpg": { caption: "untitled", order: 21 },
  "itp-ph-12-sq.jpg": { caption: "pipes", order: 22 },
  "itp-ph-11-sq.jpg": { caption: "astratto", order: 23 },
  "itp-ph-07-wd.jpg": { caption: "door", order: 24 },
  "itp-ph-04-wd.jpg": { caption: "blank", order: 25 },
  "itp-ph-06-wd.jpg": { caption: "", order: 26 },
  "itp-ph-08-wd.jpg": { caption: "", order: 27 },
  "itp-ph-09-wd.jpg": { caption: "", order: 28 },
  "itp-ph-11-wd.jpg": { caption: "", order: 29 },
  "itp-ph-13-sq.jpg": { caption: "", order: 30 },
  "itp-ph-15-wd.jpg": { caption: "", order: 31 },
}

/**
 * [
  { name: "itp-ph-02-wd.jpg", caption: "grass", order: 1 },
  { name: "itp-ph-08-sq.jpg", caption: "astratto", order: 2 },
  { name: "itp-ph-02-sq.jpg", caption: "astratto", order: 3 },
  { name: "itp-ph-03-wd.jpg", caption: "stripes", order: 4 },
  { name: "itp-ph-18-wd.jpg", caption: "19:49", order: 5 },
  { name: "itp-ph-03-sq.jpg", caption: "astratto", order: 6 },
  { name: "itp-ph-04-sq.jpg", caption: "astratto", order: 7 },
  { name: "itp-ph-19-wd.jpg", caption: "astratto", order: 8 },
  { name: "itp-ph-14-wd.jpg", caption: "rain", order: 9 },
  { name: "itp-ph-10-sq.jpg", caption: "Untitled", order: 10 },
  { name: "itp-ph-01-sq.jpg", caption: "astratto", order: 11 },
  { name: "itp-ph-17-wd.jpg", caption: "astratto", order: 12 },
  { name: "itp-ph-05-wd.jpg", caption: "ripped", order: 13 },
  { name: "itp-ph-05-sq.jpg", caption: "red", order: 14 },
  { name: "itp-ph-06-sq.jpg", caption: "astratto", order: 15 },
  { name: "itp-ph-12-wd.jpg", caption: "astratto", order: 16 },
  { name: "itp-ph-13-wd.jpg", caption: "untitled", order: 17 },
  { name: "itp-ph-07-sq.jpg", caption: "untitled", order: 18 },
  { name: "itp-ph-09-sq.jpg", caption: "astratto", order: 19 },
  { name: "itp-ph-10-wd.jpg", caption: "astratto", order: 20 },
  { name: "itp-ph-16-wd.jpg", caption: "untitled", order: 21 },
  { name: "itp-ph-12-sq.jpg", caption: "pipes", order: 22 },
  { name: "itp-ph-11-sq.jpg", caption: "astratto", order: 23 },
  { name: "itp-ph-07-wd.jpg", caption: "door", order: 24 },
  { name: "itp-ph-04-wd.jpg", caption: "blank", order: 25 },
  { name: "itp-ph-06-wd.jpg", caption: "", order: 26 },
  { name: "itp-ph-08-wd.jpg", caption: "", order: 27 },
  { name: "itp-ph-09-wd.jpg", caption: "", order: 28 },
  { name: "itp-ph-11-wd.jpg", caption: "", order: 29 },
  { name: "itp-ph-13-sq.jpg", caption: "", order: 30 },
  { name: "itp-ph-15-wd.jpg", caption: "", order: 31 },
]
 */
