export const cards = [
  {
    master: true,
    expanded: false,
    href: "#",
    title: "",
    subtitle: "",
    body: "",
    tags: [],
    heroImg: "",
    heroAlt: "",
  },
  {
    master: false,
    expanded: false,
    href: "/resume/",
    title: "Résumé",
    subtitle: "work",
    body: "Read more about my current & past activities.",
    tags: ["résumé & cv"],
    heroImg: "",
    heroAlt: "",
  },
  {
    master: false,
    expanded: true,
    href: "/archive/simplest/",
    title: "Simplest",
    subtitle: "work · 2011–2016",
    body: "My one-man-band user interface design studio.",
    tags: ["UI Design"],
    heroImg: "/img/spl-hero.jpg",
    heroAlt: "Simplest UI Design",
  },
  {
    master: false,
    expanded: true,
    href: "/archive/geekville/en/",
    title: "Geekville",
    subtitle: "work · 2013–2016",
    body: "A coworking space for tech & creative professionals.",
    tags: ["entrepreneurship"],
    heroImg: "/img/gvl-hero.jpg",
    heroAlt: "A view of Geekville",
  },
  {
    master: false,
    expanded: true,
    href: "/archive/the-collective/",
    title: "The Collective",
    subtitle: "work · 2012–2013",
    body: "The first authentic coworking space in Verona.",
    tags: ["community"],
    heroImg: "/img/tc-tshirt-2.jpg",
    heroAlt: "The Collective T-Shirt",
  },
  {
    master: false,
    expanded: true,
    href: "/archive/the-digital-league/",
    title: "The Digital League",
    subtitle: "work · 2011–2013",
    body: "A community for tech pros & innovators in the Verona area.",
    tags: ["community"],
    heroImg: "/img/tdl-hero.jpg",
    heroAlt: "The Digital League's Community",
  },
  {
    master: false,
    expanded: true,
    href: "/projects/itakepictures/",
    title: "I take pictures",
    subtitle: "projects",
    body: "A mini-site for my experiments in photography.",
    tags: ["photography"],
    heroImg: "/img/itp-ph-05-sq.jpg",
    heroAlt: "Abstract photography by Alessandro Di Tecco",
  },
  {
    master: false,
    expanded: false,
    href: "/blog",
    title: "Blog",
    subtitle: "projects",
    body: "Thoughts about technology, web development, and more.",
    tags: ["writing"],
    heroImg: "",
    heroAlt: "",
  },
]
