
#############################################################
#                                                           #
# Restart the server/watch service to apply config changes! #
#                                                           #
#############################################################


# ---------------------------------
# places
# ---------------------------------

source: ./
destination: ../../public
layouts_dir: ./_layouts
includes_dir: ./_includes


# ---------------------------------
# vars
# ---------------------------------

title: Alessandro Di Tecco, Interface designer & entrepreneur
name: The personal website of Alessandro Di Tecco
description: Alessandro Di Tecco is an interface designer and entrepreneur. This is his personal website.


# ---------------------------------
# compilers, plugins
# ---------------------------------

plugins:
  - jekyll-pug
  - jekyll-autoprefixer

jekyll-pug:
  minify: true
  debug: true
  # shipped_version: 2.0.0-rc.1

autoprefixer:
  browsers:
    - last 2 versions

sass:
  sass_dir: _sass
  style: compressed

kramdown:
  auto_ids: false


# ---------------------------------
# debugging
# ---------------------------------

error_mode: warn

##################################
# comment-out prior to deployment!

# all dirs:
# exclude: [ archive, basecamp, blog, _posts, projects, resume ]
